---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: cnrancher/fluentd
    tag: ${DRONE_TAG}-linux-amd64
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote

node:
  instance: agent-amd64
---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.2
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - SERVERCORE_VERSION=1809
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: cnrancher/fluentd
      tag: ${DRONE_TAG}-windows-1809
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote

node:
  instance: agent-windows-1809
---
kind: pipeline
name: windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
- name: build
  pull: always
  image: rancher/dapper:v0.5.2
  commands:
  - dapper.exe -f Dockerfile-windows.dapper -d ci
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - SERVERCORE_VERSION=1903
    - ARCH=amd64
    - VERSION=${DRONE_TAG}
    context: package/windows
    custom_dns: 1.1.1.1
    dockerfile: package/windows/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: cnrancher/fluentd
    tag: ${DRONE_TAG}-windows-1903
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - tag
    ref:
    - refs/heads/master
    - refs/tags/*

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
    - promote

node:
  instance: agent-windows-1903
---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    event:
    - tag
trigger:
  event:
    exclude:
    - promote

node:
  instance: agent-amd64

depends_on:
- linux-amd64
- windows-1809
- windows-1903
