---
pipeline:
  publish-image:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: rancher/fluentd
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag
